version: '3.9'

services:

  backend:
    container_name: backend
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0"
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db

  db:
    container_name: postgresql_db
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    restart: on-failure
    depends_on:
      - db

volumes:
  pgdata: {}